name: Create tfvars file
decription: This action will create a tfvars file with all the variables and secrets from github. It will create a pipeline.auto.tfvars file in the terraform folder.
inputs:
  VARS:
    description: 'JSON string of github variables'
    required: true
  SECRETS:
    description: 'JSON string of github secrets'
    required: true
runs:
  using: "composite"
  steps:
    - name: Export
      working-directory: ./terraform
      run: |
        echo '${{ inputs.SECRETS }}' |  jq -r 'to_entries|map("\(.key|ascii_upcase)=\"\(.value|tostring)\"")|.[]' >> pipeline.auto.tfvars
        echo '${{ inputs.VARS }}' |  jq -r 'to_entries|map("\(.key|ascii_upcase)=\"\(.value|tostring)\"")|.[]' >> pipeline.auto.tfvars
      shell: bash