name: Create tfvars file
decription: Create a tfvars file that's going to be used by terraform plan/apply.
inputs:
  VARS:
    required: true
  SECRETS:
    required: true
runs:
  using: "composite"
  steps:
    - name: jq
      working-directory: ./terraform
      id: jq
      run: |
        echo '${{ inputs.SECRETS }}' |  jq -r 'to_entries|map("\(.key|ascii_upcase)=\"\(.value|tostring)\"")|.[]' >> pipeline.auto.tfvars
        echo '${{ inputs.VARS }}' |  jq -r 'to_entries|map("\(.key|ascii_upcase)=\"\(.value|tostring)\"")|.[]' >> pipeline.auto.tfvars
      shell: bash