skip-check:
# Enter checks that should be skipped.

soft-fail-on:
    - CKV2_AWS_38   # Ensure Domain Name System Security Extensions (DNSSEC) signing is enabled for Amazon Route 53 public hosted zones
    - CKV2_AWS_39   # Ensure Domain Name System (DNS) query logging is enabled for Amazon Route 53 hosted zones
    - CKV2_AWS_60   # Ensure RDS instance with copy tags to snapshots is enabled
    - CKV_AWS_91    # Ensure the ELBv2 (Application/Network) has access logging enabled
    - CKV_AWS_118   # Ensure that enhanced monitoring is enabled for Amazon RDS instances
    - CKV_AWS_129   # Ensure that respective logs of Amazon Relational Database Service (Amazon RDS) are enabled
    - CKV_AWS_131   # Ensure that ALB drops HTTP headers
    - CKV_AWS_133   # Ensure that RDS instances has backup policy
    - CKV_AWS_150   # Ensure that Load Balancer has deletion protection enabled
    - CKV_AWS_157   # Ensure that RDS instances have Multi-AZ enabled
    - CKV_AWS_161   # Ensure RDS database has IAM authentication enabled
    - CKV_AWS_184   # Ensure resource is encrypted by KMS using a customer managed Key (CMK)
    - CKV_AWS_293   # Ensure that AWS database instances have deletion protection enabled
    - CKV_AWS_329   # EFS access points should enforce a root directory
    - CKV_AWS_336   # Ensure ECS containers are limited to read-only access to root filesystems
    - CKV_AWS_353   # Ensure that RDS instances have performance insights enabled
    - CKV_AWS_354   # Ensure RDS Performance Insights are encrypted using KMS CMKs