services:
  db:
    image: mysql:8.0
    container_name: mysql
    env_file:
      - local.env
    ports:
      - "3306:3306"
    volumes:
      - dbdir:/var/lib/mysql
  app:
    image: ga:latest
    container_name: goanywhere
    depends_on:
      - db
    env_file:
      - local.env
    ports:
      - "8000-8001:8000-8001"
      - "8005-8006:8005-8006"
      - "8009-8010:8009-8010"
      - "8443:8443"
      - "8021:8021"
      - "8990:8990"
      - "8022:8022"
    volumes:
      - userdata:/opt/Fortra/GoAnywhere/userdata/
      - upgrader:/opt/Fortra/GoAnywhere/upgrader
      - configdir:/etc/Fortra/GoAnywhere/config/
      - tomcatserver:/etc/Fortra/GoAnywhere/tomcat/conf/
      - tomcatlogsdir:/opt/Fortra/GoAnywhere/tomcat/logs/
      - ghttpsrootcustomdir:/opt/Fortra/GoAnywhere/ghttpsroot/custom/
      - sharedconfig:/etc/Fortra/GoAnywhere/sharedconfig
volumes:
  dbdir:
  userdata:
  upgrader:
  configdir:
  tomcatserver:
  tomcatlogsdir:
  ghttpsrootcustomdir:
  sharedconfig: