name: generate-task-definition-json
author: Raphael Moraes
decription: Action to generate a custom task definition json file

  runs:
    using: "composite"
    steps:
      - name: composite variables
        id: cv
        run: |-
          cat > pipeline.auto.tfvars3 <<EOF
          ACCOUNT = "${{ secrets.ACCOUNT }}"
          ADMIN_DB_PASSWORD = "${{ secrets.ADMIN_DB_PASSWORD }}"
          ADMIN_DB_USERNAME = "${{ secrets.ADMIN_DB_USERNAME }}"
          BRANCH_NAME = "${{ env.BRANCH_NAME }}"
          DB_PASSWORD = "${{ secrets.DB_PASSWORD }}"
          DB_USERNAME = "${{ secrets.DB_USERNAME }}"
          ECR_IMAGE = "${{ needs.Build.outputs.ecr_registry }}/mft:${{env.IMAGE_TAG}}"
          ENV = "${{ vars.ENV }}"
          FORCE_REFRESH = "${{ vars.FORCE_REFRESH }}"
          MFT_CLUSTER = "${{ vars.MFT_CLUSTER }}"
          EOF
      - name: Print Terraform variables
        id: print
        run: cat pipeline.auto.tfvars3