skip-check:
    - CKV_AWS_157   # Ensure that RDS instances have Multi-AZ enabled
    - CKV_AWS_161   # Ensure RDS database has IAM authentication enabled
    - CKV_AWS_354   # Ensure RDS Performance Insights are encrypted using KMS CMKs
    - CKV_AWS_272   # Ensure AWS Lambda function is configured to validate code-signing
    - CKV_AWS_115   # Ensure that AWS Lambda function is configured for function-level concurrent execution limit
    - CKV_AWS_116   # Ensure that AWS Lambda function is configured for a Dead Letter Queue(DLQ)
    - CKV_AWS_117   # Ensure that AWS Lambda function is configured inside a VPC