name: Reusable workflow example

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  triage:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Random Number Generator
        id: random-number-generator
        run: echo "HELLO WORLD ${{ secrets.DB_USERNAME }}"
        shell: bash